version: '3'

services:
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mysql-db
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
    ports:
      - 3306:3306
    networks:
      - study-planning-network

  discovery-server:
    container_name: discovery-server
    build:
      context: ./discovery-server/
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8761:8761
    depends_on:
      - mysql
    networks:
      - study-planning-network

  gateway:
    container_name: gateway
    build:
      context: ./gateway/
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 80:8081
    depends_on:
      - mysql
    networks:
      - study-planning-network

  config-server:
    container_name: config-server
    build:
      context: ./config-server/
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8888:8888
    networks:
      - study-planning-network

networks:
  study-planning-network: