server:
  port: 8081

spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      routes:
        - id: analysis
          uri: lb://analysis
          predicates:
            - Path=/analysis/**
        - id: study
          uri: lb://study
          predicates:
            - Path=/study/**
